usuario john senha: johnjohn

jdbc:hsqldb:file:/home/john/workspace/conferidor_sem_banco/bdsisce/bdsisce
jdbc:hsqldb:file:G:/conferidor_sem_banco_2/bdsisce/bdsisce

drop table tb_mac;
drop table tb_setor;
drop table tb_senha;

CREATE TABLE tb_mac (

  parte_1 VARCHAR(255),
  parte_2 VARCHAR(255),
  parte_3 VARCHAR(255),
  parte_4 VARCHAR(255),
  parte_5 VARCHAR(255),
  parte_6 VARCHAR(255),
  PRIMARY KEY(parte_1, parte_2, parte_3, parte_4, parte_5, parte_6)

)

CREATE TABLE tb_setor (

	cod_setor INTEGER GENERATED BY DEFAULT AS IDENTITY,
	descricao VARCHAR(255),
	email VARCHAR(255),
	PRIMARY KEY(cod_setor)

)

CREATE TABLE tb_senha (

	senha VARCHAR(8),
	mes INTEGER,
	ano INTEGER,
	PRIMARY KEY(senha)

)